### ISSUE TITLE
feat: default value when parameter is not set

### ISSUE THREAD

**Issue by jamesbrond** [jamesbrond/todoist-template#13]
Introduce the feature to set a default value in parameterized template. The default value should be used when user doesn't set it from command line.

For example:

```yaml
tasks:
      -
        content: My Task
        due_string: {theday|today}  
```

If user runs the template without `-D theday=<value>`, the default value of `today` will be used.
